#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

# loads $PLAY_PARAMS 
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"
APP_PATH="${OPENSHIFT_REPO_DIR}demagog/target/universal/stage/bin/demagog"

chmod +x ${APP_PATH}

APP_COMMAND="${APP_PATH} $PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
"-Dconfig.resource=openshift.conf "\
"-Ddemagog.defaultUser=${DEMAGOG_ADMIN_USER} "\
"-Ddemagog.defaultPassword=${DEMAGOG_ADMIN_PASSWORD} "\
"-Ddemagog.recaptcha.publicKey=${DEMAGOG_RECAPTCHA_PUBLIC_KEY} "\
"-Ddemagog.recaptcha.privateKey=${DEMAGOG_RECAPTCHA_PRIVATE_KEY} "

echo "${APP_COMMAND}"

echo $APP_COMMAND &>> $LOG_FILE
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
